services:
  sg-slam:
    build: .
    image: sg-slam   # build and tag as sg-slam or use build: .
    container_name: sg-slam
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/DATA:/ros_ws/data
      - /home/acosta/2DPASS:/ros_ws/data/2DPASS
      - /home/acosta/SG-SLAM:/ros_ws/src/SG-SLAM
    tty: true
    stdin_open: true
    restart: unless-stopped


    # docker compose up -d --build
    # docker compose exec sg-slam /bin/bash